targets:
  $default:
    builders:
      source_gen:combining_builder:
        generate_for:
          - '**_dto.dart'
          - '**_model.dart'
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/generated/{{}}.g.dart'
          ignore_for_file:
            - cast_nullable_to_non_nullable
            - avoid_annotating_with_dynamic

      json_serializable:
        generate_for:
          - '**_dto.dart'
        options:
          checked: true
          create_factory: false
          create_to_json: false

      mek_data_class_generator:data_class:
        generate_for:
          - '**_dto.dart'
          - '**_model.dart'
        options:
          page_width: 100
          fields_class_visible: false
